# Generated by Django 2.2.6 on 2019-12-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_excel_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_excel',
            name='uploaded_by',
        ),
    ]
