# Generated by Django 2.2.6 on 2019-12-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20191217_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='DOB',
            field=models.DateTimeField(null=True),
        ),
    ]
