# Generated by Django 2.2.6 on 2019-12-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20191217_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_excel',
            name='sheet',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
