# Generated by Django 2.2.6 on 2019-12-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20191217_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.City')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.State')),
            ],
        ),
    ]
