# Generated by Django 2.2.6 on 2019-12-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhaarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='adhaar_no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.AdhaarList'),
        ),
    ]
