# Generated by Django 3.0.1 on 2019-12-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20191221_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_excel',
            name='sheet',
            field=models.FileField(null=True, upload_to='excel_sheets/'),
        ),
    ]
